03.web/04. django/web_app2/blog/urls.py
from django.urls import path, re_path
from blog.views import *
app_name = 'blog'

urlpatterns = [
     path('', PostLV.as_view(), name='index'),
     # re_path(r'^(?P<slug>[-\w]+)/$', PostDV.as_view(), name='detail'),
     path('<int:pk>/', PostDV.as_view(), name='detail'),
     # Example: /blog/archive/
     path('archive/', PostAV.as_view(), name='post_archive'),
     # Example: /blog/archive/2019/
     path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
     # Example: /blog/archive/2019/nov/
     path('archive/<int:year>/<str:month>/',
          PostMAV.as_view(), name='post_month_archive'),
     # Example: /blog/archive/2019/nov/10/
     path('archive/<int:year>/<str:month>/<int:day>/',
          PostDAV.as_view(), name='post_day_archive'),
     # Example: /blog/archive/today/
     path('archive/today/', PostTAV.as_view(), name='post_today_archive'),
     # Example: /blog/tag/
     path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
     # Example: /blog/tag/tagname/
     path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),
     # Example: /blog/search/
     path('search/', SearchFormView.as_view(), name='search'),
     # Example: /blog/add/
     path('add/', PostCreateView.as_view(), name="add"),
     # Example: /blog/99/update/
     path('<int:pk>/update/', PostUpdateView.as_view(), name="update"),
     # Example: /blog/99/delete/
     path('<int:pk>/delete/', PostDeleteView.as_view(), name="delete"),
     ]

03.web/04. django/web_app2/bookmark/urls.py
from django.urls import path
from bookmark.views import *

app_name = 'bookmark' # 해당 애플리케이션의 네임스페이스명
urlpatterns = [
path('', BookmarkLV.as_view(), name='index'),
path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
# Example: /bookmark/add/
path('add/', BookmarkCreateView.as_view(), name="add"),
# Example: /bookmark/change/
path('change/', BookmarkChangeLV.as_view(), name="change"),
# Example: /bookmark/99/update/
path('<int:pk>/update/', BookmarkUpdateView.as_view(), name="update"),
# Example: /bookmark/99/delete/
path('<int:pk>/delete/', BookmarkDeleteView.as_view(), name="delete"),
]

03.web/04. django/web_app2/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    # 로그인, 로그아웃, 비밀번호 변경 등 담당
    path('accounts/', include('django.contrib.auth.urls')),
    # 회원 가입 및 처리
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(),
    name='register_done'),
    
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),

    path('tinymce/', include('tinymce.urls')),
]

03.web/04. django/web_app2/templates/base.html
{%load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Django Web Programming{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:90px;">
    {% include 'menu.html' %}
    <div class="container">
        {% block content%}{% endblock %}
    </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js">
</script>
{% block extra-script %}{% endblock %}

</html>

03.web/04. django/web_app2/templates/home.html
{% extends "base.html" %}
{% block title%}Home{% endblock %}
{% block content%}
<h1>홈 페이지</h1>
{% endblock %}

03.web/04. django/web_app2/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">
        Django - Python Web Programming</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a>
            </li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'blog:index' %}">Blog</a>
            </li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="">Photo</a>
            </li>

            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
                    <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
                </div>
            </li>
        </ul>
        <!-- <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
            </form> -->

        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn btn-primary">
                {% if user.is_active %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>
                    {{user.username }} </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    <a class="dropdown-item" href="{% url 'password_change' %}">
                        Change Password</a>
                </div>
                {% else %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>Anonymous</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                </div>
                {% endif %}
            </li>
        </ul>

    </div>
</nav>