03.web/04. django/web_app2/blog/urls.py
from django.urls import path, re_path
from blog.views import *
app_name = 'blog'

urlpatterns = [
     path('', PostLV.as_view(), name='index'),
     # re_path(r'^(?P<slug>[-\w]+)/$', PostDV.as_view(), name='detail'),
     path('<int:pk>/', PostDV.as_view(), name='detail'),
     # Example: /blog/archive/
     path('archive/', PostAV.as_view(), name='post_archive'),
     # Example: /blog/archive/2019/
     path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
     # Example: /blog/archive/2019/nov/
     path('archive/<int:year>/<str:month>/',
          PostMAV.as_view(), name='post_month_archive'),
     # Example: /blog/archive/2019/nov/10/
     path('archive/<int:year>/<str:month>/<int:day>/',
          PostDAV.as_view(), name='post_day_archive'),
     # Example: /blog/archive/today/
     path('archive/today/', PostTAV.as_view(), name='post_today_archive'),
     # Example: /blog/tag/
     path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
     # Example: /blog/tag/tagname/
     path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),
     # Example: /blog/search/
     path('search/', SearchFormView.as_view(), name='search'),
     # Example: /blog/add/
     path('add/', PostCreateView.as_view(), name="add"),
     # Example: /blog/99/update/
     path('<int:pk>/update/', PostUpdateView.as_view(), name="update"),
     # Example: /blog/99/delete/
     path('<int:pk>/delete/', PostDeleteView.as_view(), name="delete"),
     ]

03.web/04. django/web_app2/bookmark/urls.py
from django.urls import path
from bookmark.views import *

app_name = 'bookmark' # 해당 애플리케이션의 네임스페이스명
urlpatterns = [
path('', BookmarkLV.as_view(), name='index'),
path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
# Example: /bookmark/add/
path('add/', BookmarkCreateView.as_view(), name="add"),
# Example: /bookmark/change/
path('change/', BookmarkChangeLV.as_view(), name="change"),
# Example: /bookmark/99/update/
path('<int:pk>/update/', BookmarkUpdateView.as_view(), name="update"),
# Example: /bookmark/99/delete/
path('<int:pk>/delete/', BookmarkDeleteView.as_view(), name="delete"),
]

03.web/04. django/web_app2/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    # 로그인, 로그아웃, 비밀번호 변경 등 담당
    path('accounts/', include('django.contrib.auth.urls')),
    # 회원 가입 및 처리
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(),
    name='register_done'),
    
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),

    path('tinymce/', include('tinymce.urls')),
]

03.web/04. django/web_app2/bookmark/models.py
from django.db import models
from django.contrib.auth.models import User


class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)

    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

# Create your models here.

03.web/04. django/web_app2/bookmark/views.py
from typing import ClassVar
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin
# Create your views here.


class BookmarkLV(ListView):
    model = Bookmark


class BookmarkDV(DetailView):
    model = Bookmark


class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']  # 폼 모델에 사용할 필드 -> 폼 모델 자동 생성
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)


class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']  # 폼 모델에 사용할 필드 -> 폼 모델 자동 생성
    success_url = reverse_lazy('bookmark:index')


class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

03.web/04. django/web_app2/bookmark/templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}

{% block title %}bookmark_change_list.html{% endblock %}

{% block content %}

<h1>Bookmark Change - {{user}}</h1>
<br>
<table class="table table-bordered table-condensed table-striped">
    <thead>
        <tr class="table-primary">
            <th>Title</th>
            <th>Url</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.url }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'bookmark:update' item.id %}">
                    <i class="far fa-edit"></i> 수정</a>
                </a></td>
            <td><a href="{% url 'bookmark:delete' item.id %}">
                    <i class="fas fa-trash"></i> 삭제</a>
                </a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

03.web/04. django/web_app2/bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}

<h1>Bookmark Delete</h1>
<br>
<form action="." method="post">{% csrf_token %}
<p>Are you sure you want to delete "{{ object }}" ?</p>
<input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
</form>
</div>

{% endblock %}

03.web/04. django/web_app2/bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}bookmark_detail.html{% endblock %}

{% block content %}

    <h1>{{ object.title }}</h1>

    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>

    <a href="{% url 'bookmark:index' %}">목록으로</a>

{% endblock %}

03.web/04. django/web_app2/bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}bookmark_form.html{% endblock %}

{% block content %}

<h1>Bookmark Create/Update - {{user}}</h1>
<p class="font-italic">This is a creation or update form for your bookmark.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">
        Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}
<form action="." method="post" class="card pt-3">{% csrf_token %}
    <div class="form-group row">
        {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.title|add_class:"form-control"|attr:"autofocus" }}
        </div>
    </div>
    <div class="form-group row">
        {{ form.url|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.url|add_class:"form-control" }}
        </div>
    </div>
    <div class="form-group">
        <div class="offset-sm-2 col-sm-5">
            <input type="submit" value="Submit" class="btn btn-info" />
        </div>
    </div>
</form>
{% endblock %}

03.web/04. django/web_app2/bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{% block title %}bookmark_list.html{% endblock %}

{% block content %}

    <h1>Bookmark List</h1>
    <br>
    <ul>
        {% for bookmark in object_list %}
        <li><a href="{% url 'bookmark:detail' bookmark.id %}">
                {{ bookmark }}</a></li>
        {% endfor %}
    </ul>

    <div>
        {% if user.is_active %}
        <a href="{%url 'bookmark:add' %}" class="btn btn-primary btn-sm"><i class="fas fa-pencil-alt"></i> 쓰기</a>

        <a href="{% url 'bookmark:change'%}" class="btn btn-primary btn-sm"><i class="far fa-edit"></i> 수정 목록</a>
        {% endif %}
    </div>

{% endblock %}