03.web/04. django/web_app2/blog/urls.py
from django.urls import path, re_path
from blog.views import *
app_name = 'blog'

urlpatterns = [
     path('', PostLV.as_view(), name='index'),
     # re_path(r'^(?P<slug>[-\w]+)/$', PostDV.as_view(), name='detail'),
     path('<int:pk>/', PostDV.as_view(), name='detail'),
     # Example: /blog/archive/
     path('archive/', PostAV.as_view(), name='post_archive'),
     # Example: /blog/archive/2019/
     path('archive/<int:year>/', PostYAV.as_view(), name='post_year_archive'),
     # Example: /blog/archive/2019/nov/
     path('archive/<int:year>/<str:month>/',
          PostMAV.as_view(), name='post_month_archive'),
     # Example: /blog/archive/2019/nov/10/
     path('archive/<int:year>/<str:month>/<int:day>/',
          PostDAV.as_view(), name='post_day_archive'),
     # Example: /blog/archive/today/
     path('archive/today/', PostTAV.as_view(), name='post_today_archive'),
     # Example: /blog/tag/
     path('tag/', TagCloudTV.as_view(), name='tag_cloud'),
     # Example: /blog/tag/tagname/
     path('tag/<str:tag>/', TaggedObjectLV.as_view(), name='tagged_object_list'),
     # Example: /blog/search/
     path('search/', SearchFormView.as_view(), name='search'),
     # Example: /blog/add/
     path('add/', PostCreateView.as_view(), name="add"),
     # Example: /blog/99/update/
     path('<int:pk>/update/', PostUpdateView.as_view(), name="update"),
     # Example: /blog/99/delete/
     path('<int:pk>/delete/', PostDeleteView.as_view(), name="delete"),
     ]

03.web/04. django/web_app2/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    # 로그인, 로그아웃, 비밀번호 변경 등 담당
    path('accounts/', include('django.contrib.auth.urls')),
    # 회원 가입 및 처리
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(),
    name='register_done'),
    
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),

    path('tinymce/', include('tinymce.urls')),
]

03.web/04. django/web_app2/blog/models.py
from django.db import models
from django.urls import reverse

from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils.text import slugify
from tinymce.models import HTMLField


class Post(models.Model):

    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True,
                            help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100,
                                   blank=True, help_text='simple description text.')
    content = HTMLField('CONTENT')  # models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
    tags = TaggableManager(blank=True)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:

        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'  # 테이블명 재정의
        ordering = ('-modify_dt',)  # orderby 절, -이면 내림차순

    def __str__(self):
        return self.title

    def get_absolute_url(self):  # 현재 데이터의 절대 경로 추출
        # return reverse('blog:detail', args=(self.slug,))
        return reverse('blog:detail', args=(self.id,))

    def get_previous(self):  # 이전 데이터 추출
        return self.get_previous_by_modify_dt()

    def get_next(self):  # 다음 데이터 추출
        return self.get_next_by_modify_dt()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)


class PostAttachFile(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name="files", verbose_name='Post', blank=True, null=True)
    upload_file = models.FileField(
        upload_to="%Y/%m/%d", null=True, blank=True, verbose_name='파일')
    filename = models.CharField(max_length=64, null=True, verbose_name='첨부파일명')
    content_type = models.CharField(
        max_length=128, null=True, verbose_name='MIME TYPE')
    size = models.IntegerField('파일 크기')

    def __str__(self):
        return self.filename

03.web/04. django/web_app2/blog/forms.py
from django import forms


class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

03.web/04. django/web_app2/blog/views.py
from django.http import response
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView, TemplateView
from blog.models import Post, PostAttachFile
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView
from django.views.generic import FormView
from django.db.models import Q
from django.shortcuts import render
from blog.forms import PostSearchForm
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin


# ListView
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'  # 템플릿 파일명 변경
    context_object_name = 'posts'  # 컨텍스트 객체 이름 변경(object_list)
    paginate_by = 2  # 페이지네이션, 페이지당 문서 건 수


# DetailView
class PostDV(DetailView):
    model = Post


# ArchiveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'
    month_format = '%m'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'
    month_format = '%m'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'
    month_format = '%m'


# --- Tag View
class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'


class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context


#--- FormView
class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        post_list = Post.objects.filter(
            Q(title__icontains=searchWord) |
            Q(description__icontains=searchWord) |
            Q(content__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list
        return render(self.request, self.template_name, context)

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tags']
    initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('blog:index')
    
    def form_valid(self, form):
        form.instance.owner = self.request.user

        response= super().form_valid(form) # Post모델 저장, self.object

        # 업로드 파일 얻기
        files=self.request.FILES.getlist("files")
        for file in files:
            attach_file=PostAttachFile(post=self.object,filename=file.name, size=file.size,content_type=file.content_type,upload_file=file)
            attach_file.save()
        return response


class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tags']
    success_url = reverse_lazy('blog:index')
    
class PostDeleteView(OwnerOnlyMixin, DeleteView) :
    model = Post
    success_url = reverse_lazy('blog:index')

03.web/04. django/web_app2/blog/templates/blog/post_all.html
{% extends "base.html" %}

{% block title %}post_all.html{% endblock %}

{% block content %}

<h1>Blog List</h1>
<br>

{% for post in posts %}
<h3><a href='{{ post.get_absolute_url }}' target="_blank">
        {{ post.title }}</a></h3>
{{ post.modify_date|date:"N d, Y" }}
<p>{{ post.description }}</p>
{% endfor %}
<br>
<div>
    <span>
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>

</div>
{% if user.is_active %}
<div class="text-right mr-3">
    <a href="{%url 'blog:add' %}" class="btn btn-primary btn-sm">
        <i class="fas fa-pencil-alt"></i> 쓰기</a>
</div>
{% endif %}

{% endblock %}

03.web/04. django/web_app2/blog/templates/blog/post_archive.html
{% extends "base.html" %}
{% block title %}post_archive.html{% endblock %}
{% block content %}
<h1>Post Archives until {% now "b d, Y" %}</h1>
{% for date in date_list %}
<a href="{% url 'blog:post_year_archive' date|date:'Y' %}" class="btn btn-outline-primary btn-sm mx-1">
    Year-{{ date|date:"Y" }}</a>
{% endfor %}
<br><br>
<div>
    <ul>
        {% for post in object_list %}
        <li class="h5">
            {{ post.modify_dt|date:"Y-m-d" }}&emsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

03.web/04. django/web_app2/blog/templates/blog/post_archive_day.html
{% extends "base.html" %}
{% block title %}post_archive_day.html{% endblock %}
{% block content %}
<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>
<br><br>
<div>
    <ul>
        {% for post in object_list %}
        <li class="h5">
            {{ post.modify_dt|date:"Y-m-d" }}&emsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

03.web/04. django/web_app2/blog/templates/blog/post_archive_month.html
{% extends "base.html" %}
{% block title %}post_archive_month.html{% endblock %}
{% block content %}
<h1>Post Archives for {{ month|date:"N, Y" }}</h1>
<br><br>
<div>
    <ul>
        {% for post in object_list %}
        <li class="h5">
            {{ post.modify_dt|date:"Y-m-d" }}&emsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

03.web/04. django/web_app2/blog/templates/blog/post_archive_today.html
<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>
<div>
    <ul>
        {% for post in object_list %}
        <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>

03.web/04. django/web_app2/blog/templates/blog/post_archive_year.html
{% extends "base.html" %}
{% block title %}post_archive_year.html{% endblock %}
{% block content %}
<h1>Post Archives for {{ year|date:"Y" }}</h1>
{% for date in date_list %}
<a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'b' %}" class="btn btn-outline-primary btn-sm mx-1">
    {{ date|date:"F" }}</a>
{% endfor %}
<br><br>
<div>
    <ul>
        {% for post in object_list %}
        <li class="h5">
            {{ post.modify_dt|date:"Y-m-d" }}&emsp;
            <a href="{{ post.get_absolute_url }}">
                <strong>{{ post.title }}</strong></a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

03.web/04. django/web_app2/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}post_confirm_delete.html{% endblock %}

{% block content %}

<h1>Post Delete</h1>
<br>

    <form action="." method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>

{% endblock %}

03.web/04. django/web_app2/blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% block title %}post_detail.html{% endblock %}
{% block content %}
<h2>{{ object.title }}</h2>
<p>
    {% if object.get_next %}
    <a href="{{ object.get_next.get_absolute_url }}" title="View previous post">
        <i class="fas fa-arrow-circle-left"></i> {{ object.get_next }}
    </a>
    {% endif %}
    {% if object.get_previous %}
    | <a href="{{ object.get_previous.get_absolute_url }}" title="View next post">
        {{ object.get_previous }} <i class="fas fa-arrow-circle-right"></i>
    </a>
    {% endif %}
</p>
<div>{{ object.modify_dt|date:"j F Y" }}</div>
<br>
<p>작성자 : {{ object.owner.username }} </p>
<br>
<div>
    {{ object.content|safe }}
</div>

<br>
<div>
    <b>TAGS</b> <i class="fas fa-tag"></i>
    {% load taggit_templatetags2_tags %}
    {% get_tags_for_object object as "tags" %}
    {% for tag in tags %}
    <a href="{% url 'blog:tagged_object_list' tag.name %}">#{{tag.name}}</a>
    {% endfor %}
    &emsp;<a href="{% url 'blog:tag_cloud' %}">
        <span class="btn btn-info btn-sm">TagCloud</span> </a>
</div>
{% if user == object.owner %}
<div class="text-right">
    <a href="{% url 'blog:update' post.id %}" class="mr-3">
        <i class="far fa-edit"></i> 수정</a>
    <a href="{% url 'blog:delete' post.id %}" class="text-danger mr-3">
        <i class="fas fa-trash"></i> 삭제</a>
</div>
{% endif %}

{% endblock %}

03.web/04. django/web_app2/blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}post_form.html{% endblock %}
{% block content %}
<h1>Post Create/Update - {{user}}</h1>
<p class="font-italic">This is a creation or update form for your post.</p>
{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">
        Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}
<form action="." method="post" enctype="multipart/form-data" class="card pt-3">{% csrf_token %}
    <div class="form-group row">
        {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.title|add_class:"form-control"|attr:"autofocus" }}
        </div>
    </div>

    <div class="form-group row">
        {{ form.slug|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.slug|add_class:"form-control"|attr:"readonly" }}
        </div>
        <small class="form-text text-muted">{{ form.slug.help_text }}</small>
    </div>

    <div class="form-group row">
        {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.description|add_class:"form-control" }}
        </div>
        <small class="form-text text-muted">
            {{ form.description.help_text }}</small>
    </div>

    <div class="form-group row">
        <label for="files" class="col-form-label col-sm-2 ml-3 font-weight-bold">첨부 파일 :</label>
        <div class="col-sm-8 ">
            <input type="file" id="files" name="files" multiple>
        </div>
    </div>

    <div class="form-group row">
        {{ form.content|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-8">
            {{ form.content|add_class:"form-control" }}
        </div>
    </div>
    <div class="form-group row">
        {{ form.tags|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.tags|add_class:"form-control" }}
        </div>
        <small class="form-text text-muted">{{ form.tags.help_text }}</small>
    </div>
    <div class="form-group">
        <div class="offset-sm-2 col-sm-5">
            <input type="submit" value="Submit" class="btn btn-info" />
        </div>
    </div>
</form>
{% endblock %}

{% block extra-script %}
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: 'textarea',
        menubar: false,
        statusbar: false,
        toolbar1: 'formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify | numlist bullist outdent indent | removeformat'
    });
</script>
{% endblock %}

03.web/04. django/web_app2/blog/templates/blog/post_search.html
{% extends "base.html" %}

{% block title %}post_search.html{% endblock %}

{% block content %}

<h1>Blog Search</h1>
<br>
<form action="." method="post"> {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn btn-primary btn-sm">
</form>

<br /><br />

    {% if object_list %}
        {% for post in object_list %}
        <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
        {{ post.modify_dt|date:"N d, Y" }}
        <p>{{ post.description }}</p>
        {% endfor %}

    {% elif search_term %}
    <b><i>Search Word({{ search_term }}) Not Found !</i></b>
    {% endif %}
    
{% endblock %}